name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          #- windows-latest
        raku-version:
          - 'latest'
          - '2022.07'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Libraries (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libfreetype6-dev
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get install -y libfontconfig-dev
      - name: Install Libraries (MacOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew update
          brew install freetype
          brew install harfbuzz
          brew install openssl
          brew install fontconfig
          brew install cairo
          zef install MacOS::NativeLib
          ensure-symlink-for cairo
      - name: Install Dependencies
        run: |
          zef install --/test App::Prove6
          zef --deps-only install .
      - name: Run Tests
        run: |
          prove6 -I. t
          zef install .
